FROM public.ecr.aws/lambda/python:3.11

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY api.py .
COPY predict.py .
COPY food_health_regressor.pkl .
COPY food_database.json .

CMD ["api.handler"]